# Generated by Django 2.2.6 on 2019-12-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_robot', models.BooleanField(default=False)),
                ('is_guest', models.BooleanField(default=False)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.TextField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(default=1500.0)),
                ('total_score', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('max_speed', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TetrisRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.IntegerField()),
                ('type', models.CharField(choices=[('CL', 'Classic'), ('DM', 'Deathmatch'), ('TA', 'Time Attack'), ('SA', 'Score Attack'), ('DR', 'Drag Racing'), ('AC', 'Accelerate'), ('CF', 'Captue the Flag')], max_length=2)),
                ('players_at_positions', models.TextField(default='')),
                ('active_players', models.ManyToManyField(to='web.Player')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_room', to='web.Player')),
            ],
        ),
        migrations.CreateModel(
            name='SingleGameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CL', 'Classic'), ('DM', 'Deathmatch'), ('TA', 'Time Attack'), ('SA', 'Score Attack'), ('DR', 'Drag Racing'), ('AC', 'Accelerate'), ('CF', 'Captue the Flag')], max_length=2)),
                ('players', models.ManyToManyField(related_name='user_games', to='web.Player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_wins', to='web.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Player')),
            ],
        ),
    ]
