# Generated by Django 2.2.6 on 2019-12-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_robot', models.BooleanField()),
                ('joined', models.DateTimeField()),
                ('rating', models.FloatField()),
                ('total_score', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('max_speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
                ('joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamGameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CL', 'Classic'), ('DM', 'Deathmatch'), ('TA', 'Time Attack'), ('SA', 'Score Attack'), ('DR', 'Drag Racing'), ('AC', 'Accelerate'), ('CF', 'Captue the Flag')], max_length=2)),
                ('teams', models.ManyToManyField(related_name='team_games', to='web.Team')),
                ('winner_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_wins', to='web.Team')),
            ],
        ),
        migrations.CreateModel(
            name='SingleGameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CL', 'Classic'), ('DM', 'Deathmatch'), ('TA', 'Time Attack'), ('SA', 'Score Attack'), ('DR', 'Drag Racing'), ('AC', 'Accelerate'), ('CF', 'Captue the Flag')], max_length=2)),
                ('players', models.ManyToManyField(related_name='user_games', to='web.Player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_wins', to='web.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Team'),
        ),
    ]
