# Generated by Django 2.2.6 on 2020-03-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='LI_games',
            field=models.FloatField(default=0.0),
        ),
    ]
