# Generated by Django 2.2.6 on 2019-12-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_robot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='max_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
