# Generated by Django 2.2.6 on 2019-12-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetrisroom',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
