# Generated by Django 2.2.6 on 2020-03-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_singlegamerecord_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetrisroom',
            name='start_players',
            field=models.TextField(default=''),
        ),
    ]
