# Generated by Django 2.2.6 on 2019-12-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_tetrisroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tetrisroom',
            name='players',
            field=models.IntegerField(),
        ),
    ]
