# Generated by Django 2.2.6 on 2020-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_tetrisroom_start_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlegamerecord',
            name='graphs',
            field=models.TextField(default=''),
        ),
    ]
