# Generated by Django 2.2.6 on 2020-03-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_singlegamerecord_graphs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_robot',
        ),
    ]
