# Generated by Django 2.2.6 on 2020-02-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_tetrisroom_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='singlegamerecord',
            name='players',
        ),
        migrations.RemoveField(
            model_name='singlegamerecord',
            name='winner',
        ),
        migrations.AddField(
            model_name='singlegamerecord',
            name='positions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='singlegamerecord',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='singlegamerecord',
            name='type',
            field=models.CharField(choices=[('CL', 'Classic'), ('DM', 'Deathmatch'), ('SU', 'Survival'), ('LI', 'Lines'), ('CO', 'Countdown'), ('SA', 'Score Attack'), ('DR', 'Drag Racing'), ('AC', 'Accelerate'), ('CF', 'Capture the Flag'), ('RA', 'Rally')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tetrisroom',
            name='type',
            field=models.CharField(choices=[('CL', 'Classic'), ('DM', 'Deathmatch'), ('SU', 'Survival'), ('LI', 'Lines'), ('CO', 'Countdown'), ('SA', 'Score Attack'), ('DR', 'Drag Racing'), ('AC', 'Accelerate'), ('CF', 'Capture the Flag'), ('RA', 'Rally')], max_length=2),
        ),
    ]
