# Generated by Django 2.2.6 on 2019-12-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20191213_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tetrisroom',
            name='active_players',
            field=models.ManyToManyField(blank=True, null=True, to='web.Player'),
        ),
        migrations.AlterField(
            model_name='tetrisroom',
            name='active_teams',
            field=models.ManyToManyField(blank=True, null=True, to='web.Team'),
        ),
    ]
