# Generated by Django 2.2.6 on 2020-06-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_player_is_robot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_countdown_score_REC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_countdown_score_REC', to='web.SingleGameRecord')),
                ('best_distance_REC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_distance_REC', to='web.SingleGameRecord')),
                ('best_lines_count_REC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_lines_count_REC', to='web.SingleGameRecord')),
                ('best_score_REC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_score_REC', to='web.SingleGameRecord')),
                ('best_speed_REC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_speed_REC', to='web.SingleGameRecord')),
                ('best_survival_time_REC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_survival_time_REC', to='web.SingleGameRecord')),
                ('best_time_acc_REC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_time_acc_REC', to='web.SingleGameRecord')),
                ('best_time_climb_REC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_time_climb_REC', to='web.SingleGameRecord')),
                ('best_time_drag_REC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_time_drag_REC', to='web.SingleGameRecord')),
                ('best_time_lines_REC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_time_lines_REC', to='web.SingleGameRecord')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='record_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.PlayerRecord'),
        ),
    ]
