# Generated by Django 2.2.6 on 2019-12-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20191213_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('raw_data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='BitRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('raw_data', models.BinaryField()),
            ],
        ),
    ]
