# Generated by Django 2.2.6 on 2020-02-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200201_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='multiplayer_games_count_acc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='multiplayer_games_count_classic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='multiplayer_games_count_countdown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='multiplayer_games_count_ctf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='multiplayer_games_count_deathmatch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='multiplayer_games_count_drag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='multiplayer_games_count_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='multiplayer_games_count_rally',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='multiplayer_games_count_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='multiplayer_games_count_survival',
            field=models.IntegerField(default=0),
        ),
    ]
