# Generated by Django 2.2.6 on 2020-06-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200623_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetrisroom',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='record_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.PlayerRecord'),
        ),
    ]
