# Generated by Django 2.2.6 on 2020-06-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200624_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rating',
        ),
        migrations.AddField(
            model_name='player',
            name='AC_rating',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name='player',
            name='CF_rating',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name='player',
            name='CL_rating',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name='player',
            name='CO_rating',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name='player',
            name='DM_rating',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name='player',
            name='DR_rating',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name='player',
            name='HF_rating',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name='player',
            name='LI_rating',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name='player',
            name='RA_rating',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name='player',
            name='SA_rating',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name='player',
            name='SU_rating',
            field=models.FloatField(default=1500.0),
        ),
    ]
