# Generated by Django 2.2.6 on 2020-02-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200201_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetrisroom',
            name='proc',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='singlegamerecord',
            name='type',
            field=models.CharField(choices=[('CL', 'Classic'), ('DM', 'Deathmatch'), ('SU', 'Survival'), ('LI', 'Lines'), ('CO', 'Countdown'), ('SA', 'Score Attack'), ('DR', 'Drag Racing'), ('AC', 'Accelerate'), ('CF', 'Capture Flag'), ('HF', 'Hold Flag'), ('RA', 'Rally')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tetrisroom',
            name='type',
            field=models.CharField(choices=[('CL', 'Classic'), ('DM', 'Deathmatch'), ('SU', 'Survival'), ('LI', 'Lines'), ('CO', 'Countdown'), ('SA', 'Score Attack'), ('DR', 'Drag Racing'), ('AC', 'Accelerate'), ('CF', 'Capture Flag'), ('HF', 'Hold Flag'), ('RA', 'Rally')], max_length=2),
        ),
    ]
