# Generated by Django 2.2.6 on 2020-06-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200626_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetrisroom',
            name='crazy',
            field=models.BooleanField(default=False),
        ),
    ]
