# Generated by Django 2.2.6 on 2020-02-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200220_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetrisroom',
            name='bots',
            field=models.IntegerField(default=0),
        ),
    ]
