# Generated by Django 2.2.6 on 2020-07-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='best_distance',
            new_name='a',
        ),
    ]
