# Generated by Django 2.2.6 on 2020-02-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_tetrisroom_bots'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetrisroom',
            name='botlevels',
            field=models.TextField(default='[]'),
        ),
    ]
