# Generated by Django 2.2.6 on 2020-07-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20200713_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerrecord',
            name='best_countdown_score_REC',
        ),
        migrations.RemoveField(
            model_name='playerrecord',
            name='best_distance_REC',
        ),
        migrations.RemoveField(
            model_name='playerrecord',
            name='best_lines_count_REC',
        ),
        migrations.RemoveField(
            model_name='playerrecord',
            name='best_score_REC',
        ),
        migrations.RemoveField(
            model_name='playerrecord',
            name='best_speed_REC',
        ),
        migrations.RemoveField(
            model_name='playerrecord',
            name='best_survival_time_REC',
        ),
        migrations.RemoveField(
            model_name='playerrecord',
            name='best_time_acc_REC',
        ),
        migrations.RemoveField(
            model_name='playerrecord',
            name='best_time_climb_REC',
        ),
        migrations.RemoveField(
            model_name='playerrecord',
            name='best_time_drag_REC',
        ),
        migrations.RemoveField(
            model_name='playerrecord',
            name='best_time_lines_REC',
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='countdown_score_REC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countdown_score_REC', to='web.SingleGameRecord'),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='distance_REC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distance_REC', to='web.SingleGameRecord'),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='lines_count_REC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines_count_REC', to='web.SingleGameRecord'),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='score_REC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_REC', to='web.SingleGameRecord'),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='speed_REC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speed_REC', to='web.SingleGameRecord'),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='survival_REC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survival_REC', to='web.SingleGameRecord'),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='time_acc_REC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_acc_REC', to='web.SingleGameRecord'),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='time_climb_REC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_climb_REC', to='web.SingleGameRecord'),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='time_drag_REC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_drag_REC', to='web.SingleGameRecord'),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='time_lines_REC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_lines_REC', to='web.SingleGameRecord'),
        ),
    ]
