# Generated by Django 2.2.6 on 2020-07-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20200713_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerrecord',
            old_name='countdown_score_REC',
            new_name='best_countdown_score_REC',
        ),
        migrations.RenameField(
            model_name='playerrecord',
            old_name='distance_REC',
            new_name='best_distance_REC',
        ),
        migrations.RenameField(
            model_name='playerrecord',
            old_name='lines_count_REC',
            new_name='best_lines_count_REC',
        ),
        migrations.RenameField(
            model_name='playerrecord',
            old_name='score_REC',
            new_name='best_score_REC',
        ),
        migrations.RenameField(
            model_name='playerrecord',
            old_name='speed_REC',
            new_name='best_speed_REC',
        ),
        migrations.RenameField(
            model_name='playerrecord',
            old_name='survival_REC',
            new_name='best_survival_REC',
        ),
        migrations.RenameField(
            model_name='playerrecord',
            old_name='time_acc_REC',
            new_name='best_time_acc_REC',
        ),
        migrations.RenameField(
            model_name='playerrecord',
            old_name='time_climb_REC',
            new_name='best_time_climb_REC',
        ),
        migrations.RenameField(
            model_name='playerrecord',
            old_name='time_drag_REC',
            new_name='best_time_drag_REC',
        ),
        migrations.RenameField(
            model_name='playerrecord',
            old_name='time_lines_REC',
            new_name='best_time_lines_REC',
        ),
    ]
